Redis:
  Addr: "localhost:6379"
  Password: ""
  DB: 0

Connection:
  AccessSize: 30
  BucketTTLMilliseconds: 3000

Server:
  Sequence: 1
  Master: true
  Addr: ":8083"
  WaitingHTMLFile: "template/index.html"

Client:
  HeartbeatRedisTTLMilliseconds: 10000

Proxy:
    Addr: "localhost:9090"
    TimeoutMilliseconds: 3000
    PoolConnectionCapacityMin: 100
    PoolConnectionCapacityMax: 1000